config/routes.rb
Rails.application.routes.draw do

  mount Qa::Engine => '/qa'

  root 'login#index'

  resources :entries
  resources :concepts
  resources :places
  resources :people
  resources :groups
  resources :subjects
  resources :errors

  get 'image_zoom_large' => 'image_zoom_large#index'
  get 'image_zoom_large/alt' => 'image_zoom_large#alt'
  get 'logout' => 'login#logout'
  get 'login' => 'login#index'
  post 'login_submit' => 'login#login_submit'
  get 'login_temp' => 'login#login_temp'
  get 'timed_out' => 'login#timed_out'
  get 'landing_page' => 'landing_page#index'
  get 'browse_folios' => 'browse_folios#index'
  get 'go_entries' => 'landing_page#go_entries'
  get 'admins' => 'admins#index'

end

app/views/admins/index.html.erb
<%# Display a list of admin links for the concepts, people, groups, places and subjects %>
<div class="popup">

  <div class="popup_title">Admin</div>

  <div style="margin-top: 10px">

    <p>Concept Lists:</p>

    <div class="search_box">
      <ul class="list_admin">
        <li><%= link_to 'Date Role', concepts_path(list_type: 'date_role') %></li>
        <li><%= link_to 'Descriptor', concepts_path(list_type: 'descriptor') %></li>
        <li><%= link_to 'Entry Type', concepts_path(list_type: 'entry_type') %></li>
        <!--<li><%= link_to 'Format', concepts_path(list_type: 'format') %></li>-->
        <li><%= link_to 'Language', concepts_path(list_type: 'language') %></li>
        <li><%= link_to 'Person Role', concepts_path(list_type: 'person_role') %></li>
        <li><%= link_to 'Place Role', concepts_path(list_type: 'place_role') %></li>
        <li><%= link_to 'Place Type', concepts_path(list_type: 'place_type') %></li>
        <li><%= link_to 'Section Type', concepts_path(list_type: 'section_type') %></li>
      </ul>
    </div>

    <div style="clear: both"></div>

    <p>Person / Place Lists:</p>

    <div class="search_box">
      <ul class="listAdmin">
        <li><%= link_to 'Person List', people_path(person_field: 'none') %></li>
        <li><%= link_to 'Group List', groups_path(group_field: 'none') %></li>
        <li><%= link_to 'Place List', places_path(place_field: 'none') %></li>
      </ul>
    </div>

    <div style="clear:both"></div>

    <p>Subject List:</p>

    <div class="search_box">
      <ul class="listAdmin">
        <li><%= link_to 'Subject List', subjects_path %></li>
      </ul>
    </div>

  </div>
</div>