config/routes.rb
Rails.application.routes.draw do

  mount Qa::Engine => '/qa'

  root 'login#index'

  resources :entries
  resources :concepts
  resources :places
  resources :people
  resources :groups
  resources :subjects
  resources :errors

  get 'image_zoom_large' => 'image_zoom_large#index'
  get 'image_zoom_large/alt' => 'image_zoom_large#alt'
  get 'logout' => 'login#logout'
  get 'login' => 'login#index'
  post 'login_submit' => 'login#login_submit'
  get 'login_temp' => 'login#login_temp'
  get 'timed_out' => 'login#timed_out'
  get 'landing_page' => 'landing_page#index'
  get 'browse_folios' => 'browse_folios#index'
  get 'go_entries' => 'landing_page#go_entries'
  get 'admins' => 'admins#index'

end

app/models/group.rb
# frozen_string_literal: true

class Group < ActiveFedora::Base
  include AssignRdfTypes
  include Generic
  include DCTerms
  include RdfsSeealso
  include MadsRelauth
  include SkosLabels
  include SameAs
  include AssignId
  include RdfType

  belongs_to :concept_scheme, predicate: ::RDF::Vocab::SKOS.inScheme

  # eg. NCA Rules 4
  property :name, predicate: ::RDF::Vocab::FOAF.name, multiple: false do |index|
    index.as :stored_searchable
  end

  # eg. NCA Rules 4.4
  property :dates, predicate: ::RDF::URI.new('http://data.archiveshub.ac.uk/def/dates'), multiple: false do |index|
    index.as :stored_searchable
  end

  # eg. NCA Rules 4.4 use for places and status/function/sphere of activity designation as needed
  property :qualifier, predicate: ::RDF::URI.new('http://dlib.york.ac.uk/ontologies/generic#qualifier'), multiple: false do |index|
    index.as :stored_searchable
  end

  property :note, predicate: ::RDF::URI.new('http://dlib.york.ac.uk/ontologies/borthwick-registers#note'), multiple: true do |index|
    index.as :stored_searchable
  end

  property :group_type, predicate: ::RDF::URI.new('http://dlib.york.ac.uk/ontologies/generic#groupType'), multiple: true do |index|
    index.as :stored_searchable
  end
end

app/controllers/groups_controller.rb
# frozen_string_literal: true

class GroupsController < ApplicationController
  before_action :session_timed_out_small

  # INDEX
  def index
    # This variable identifies the 'Same As' field on the form (i.e. it is used when the user selects a 'group')
    @group_field = params[:group_field]

    # Set the search_term variable if it is passed as a parameter
    @search_term = ''
    @search_term = if !params[:search_term_index].nil?
                     params[:search_term_index]
                   else
                     params[:search_term]
                   end
    @safe_search_term = Regexp.escape(@search_term) unless @search_term.nil?
    @search_array = []

    # Get Concepts for the group ConceptScheme and filter according to search_term
    # solr_query(q, fl, rows, sort) expected parameters
    num = SolrQuery.new.solr_query('has_model_ssim:Group', 'id', 0)['response']['numFound']
    search_response = SolrQuery.new.solr_query(
      'has_model_ssim:Group',
      'id, preflabel_tesim, altlabel_tesim',
      num,
      'preflabel_si asc'
    )
    search_response['response']['docs'].map.each do |result|
      id = result['id']
      preflabel = result['preflabel_tesim'].join
      # Some groups do not have variant name
      altlabel = ''
      altlabel = result['altlabel_tesim'].join unless result['altlabel_tesim'].nil?

      tt = []
      # Select results that match group name or group variant name
      next unless preflabel.match(/#{@safe_search_term}/i) || altlabel.match(/#{@safe_search_term}/i)

      tt << id
      tt << preflabel
      @search_array << tt
    end

    # Sort the array by family
    @search_array = @search_array.sort_by { |k| k[1] }
  rescue StandardError => e
    log_error(__method__, __FILE__, e)
    raise
  end

  # SHOW
  def show; end

  # NEW
  def new
    @group = Group.new
    @search_term = params[:search_term]
    @group_field = params[:group_field]
  rescue StandardError => e
    log_error(__method__, __FILE__, e)
    raise
  end

  # EDIT
  def edit
    @group = Group.find(params[:id])
    @search_term = params[:search_term]
    @group_field = params[:group_field]
  rescue StandardError => e
    log_error(__method__, __FILE__, e)
    raise
  end

  # CREATE
  def create
    # Check parameters are permitted
    group_params = whitelist_group_params

    # Remove any empty fields
    remove_group_popup_empty_fields(group_params)

    @error = ''

    @error = 'Please enter a Name' if group_params[:name] == ''

    # Check that same_as is a URL
    @error = check_url(group_params[:same_as], @error, 'Same As')

    # Disable this check
    # Check that related_authority is a URL
    # @error = check_url(group_params[:related_authority], @error, "Related Authority")

    @group = Group.new(group_params)

    if @error != ''
      @search_term = params[:search_term]
      @group_field = params[:group_field]
      render 'new'
    else

      # Use a solr query to obtain the concept scheme id for 'groups'
      response = SolrQuery.new.solr_query(q = 'has_model_ssim:ConceptScheme AND preflabel_tesim:"groups"', fl = 'id', rows = 1, sort = '')
      id = response['response']['docs'][0]['id']
      @group.concept_scheme_id = id

      # Get preflabel, rdftype and save
      @group.preflabel = get_preflabel(@group.name, @group.dates, @group.qualifier)
      @group.rdftype << @group.add_rdf_types
      @group.save

      # If the 'Submit and Close' button has been clicked, pass these variables back to the page
      # so that the javascript method is run (i.e. post_value()) and the page is closed
      if params[:commit] == 'Submit and Close'
        @commit_id = @group.id
        @commit_group_name = group_params[:family]
      end

      redirect_to controller: 'groups', action: 'index', search_term: params[:search_term], group_field: params[:group_field]
    end
  rescue StandardError => e
    log_error(__method__, __FILE__, e)
    raise
  end

  # UPDATE
  def update
    # Check parameters are permitted
    group_params = whitelist_group_params

    # Remove any empty fields
    remove_group_popup_empty_fields(group_params)

    @error = ''

    @error = 'Please enter a Name' if group_params[:name] == ''

    # Check that same_as is a URL
    @error = check_url(group_params[:same_as], @error, 'Same As')

    # Disable this check
    # Check that related_authority is a URL
    # @error = check_url(place_params[:related_authority], @error, "Related Authority")

    # Get a group object using the id and populate it with the group parameters
    @group = Group.find(params[:id])
    @group.attributes = group_params

    if @error != ''
      @search_term = params[:search_term]
      @group_field = params[:group_field]
      render 'edit'
    else
      @group.preflabel = get_preflabel(@group.name, @group.dates, @group.qualifier)
      @group.save
      # solr update any related objects
      update_related('group', @group.id)
      redirect_to controller: 'groups', action: 'index', search_term: params[:search_term], group_field: params[:group_field]
    end
  rescue StandardError => e
    log_error(__method__, __FILE__, e)
    raise
  end

  # DESTROY
  def destroy
    @group = Group.find(params[:id])

    # Check if the group is present in any of the entries
    # If so, direct the user to a page with the entry locations so that they can remove them
    existing_location_list = get_existing_location_list('person_same_as', @group.id)

    if !existing_location_list.empty?
      render 'group_exists_list', locals: { :@group_name => @group.name, :id => @group.id, :@existing_location_list => existing_location_list, :@go_back_id => params[:go_back_id], :@search_term => params[:search_term], :@group_field => params[:group_field] }
    else
      @group.destroy
      redirect_to controller: 'groups', action: 'index', search_term: params[:search_term], group_field: params[:group_field]
    end
  rescue StandardError => e
    log_error(__method__, __FILE__, e)
    raise
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def whitelist_group_params
    params.require(:group).permit(:name, :dates, :qualifier, :group_type, same_as: [], related_authority: [], altlabel: [], note: []) # Note - arrays need to go at the end or an error occurs!
  end

  # This method is used to get the preflabel and to get the label which is displayed on the view page
  # is_join is required if the data comes from solr, i.e. when getting the data to display on the view page
  def get_preflabel(name, dates, qualifier)
    preflabel = name
    if !dates.nil? && (dates != '')
      name = "#{name}, " if name != ''
      preflabel = "#{name}, #{dates}"
    end

    preflabel += ", #{qualifier}" if !qualifier.nil? && (qualifier != '')

    preflabel
  rescue StandardError => e
    log_error(__method__, __FILE__, e)
    raise
  end
end

app/views/groups/_form.html.erb
<div class="popup">

  <%
     if @group.new_record?
       start_text = 'Add'
       form_url = 'groups_path(@group)'
       form_method = ':post'
     else
       start_text = 'Edit'
       form_url = 'group_path(@group)'
       form_method = ':patch'
     end
  %>

  <%# Display group title %>
  <div class="popup_title">
    <%= start_text %> group
  </div>

  <%# Display group errors %>
  <% if @error != nil && @error != '' %>
      <div class="popup_error"><%= @error.html_safe %></div>
  <% end %>

  <%# Add / Edit group form %>
  <div>
    <%= link_to 'Go back to search page', groups_path(:search_term => @search_term, :group_field => @group_field) %>
  </div>

  <%# Add / Edit group form %>
  <%= form_for @group, url: eval(form_url), method: eval(form_method), html: {style: 'margin-top: 15px; margin-bottom: 0px'} do |f| %>

      <div class='tab1'>

        <table cellspacing="0" style="width: 100%; font-size: 0.95em">

          <%# Name %>
          <tr>
            <th style="width: 150px">Name:</th>
            <td>
              <%= text_field_tag "group[name]", @group.name %>
            </td>
          </tr>

          <%# Dates %>
          <tr>
            <th>Dates:</th>
            <td>
              <%= text_field_tag "group[dates]", @group.dates %>
            </td>
          </tr>

          <%# Qualifier %>
          <tr>
            <th>Qualifier:</th>
            <td>
              <%= text_field_tag "group[qualifier]", @group.qualifier %>
            </td>
          </tr>

          <%# Type %>
          <tr>
            <th>Group Type:
              <%= image_tag 'plus_sign.png', :alt => 'plus icon', :class => 'plus_icon click_popup_multiple_field_button', :jq_type_1 => 'group', :jq_type_2 => 'group_type', :context_path => ENV['CONTEXT_PATH'] %>
            </th>
            <td>
              <div class="field_group">
                <% @group.group_type.each do |group_type| %>
                    <div class="field_single">
                      <%= text_field_tag 'group[group_type][]', group_type %>
                      <%= image_tag 'delete.png', :alt => 'delete icon', :class => 'delete_icon click_remove_field_level1', :jq_tag_type => 'input' %>
                    </div>
                <% end %>
              </div>
            </td>
          </tr>

          <%# Same As %>
          <tr>
            <th>Same As:
              <%= image_tag 'plus_sign.png', :alt => 'plus icon', :class => 'plus_icon click_popup_multiple_field_button', :jq_type_1 => 'group', :jq_type_2 => 'same_as', :context_path => ENV['CONTEXT_PATH'] %>
            </th>
            <td>
              <div class="same_as">
                <% @group.same_as.each do |same_as| %>
                    <div class="field_single">
                      <%= text_field_tag 'group[same_as][]', same_as %>
                      <%= image_tag 'delete.png', :alt => 'delete icon', :class => 'delete_icon click_remove_field_level1', :jq_tag_type => 'input' %>
                    </div>
                <% end %>
              </div>
            </td>
          </tr>

          <%# Related Authority %>
          <tr>
            <th>Related Authority:
              <%= image_tag 'plus_sign.png', :alt => 'plus icon', :class => 'plus_icon click_popup_multiple_field_button', :jq_type_1 => 'group', :jq_type_2 => 'related_authority', :context_path => ENV['CONTEXT_PATH'] %>
            </th>
            <td>
              <div class="field_group">
                <% @group.related_authority.each do |related_authority| %>
                    <div class="field_single">
                      <%= text_field_tag 'group[related_authority][]', related_authority %>
                      <%= image_tag 'delete.png', :alt => 'delete icon', :class => 'delete_icon click_remove_field_level1', :jq_tag_type => 'input' %>
                    </div>
                <% end %>
              </div>
            </td>
          </tr>

          <%# Variant Names %>
          <%# Note that this is 'altlabel' in the model %>
          <tr>
            <th>Variant Names:
              <%= image_tag 'plus_sign.png', :alt => 'plus icon', :class => 'plus_icon click_popup_multiple_field_button', :jq_type_1 => 'group', :jq_type_2 => 'altlabel', :context_path => ENV['CONTEXT_PATH'] %>
            </th>
            <td>
              <div class="field_group">
                <% @group.altlabel.each do |altlabel| %>
                    <div class="field_single">
                      <%= text_field_tag 'group[altlabel][]', altlabel %>
                      <%= image_tag 'delete.png', :alt => 'delete icon', :class => 'delete_icon click_remove_field_level1', :jq_tag_type => 'input' %>
                    </div>
                <% end %>
              </div>
            </td>
          </tr>

          <%# Note %>
          <tr>
            <th>Note:
              <%= image_tag 'plus_sign.png', :alt => 'plus icon', :class => 'plus_icon click_popup_multiple_field_button', :jq_type_1 => 'group', :jq_type_2 => 'note', :context_path => ENV['CONTEXT_PATH'] %>
            </th>
            <td>
              <div class="note">
                <% @group.note.each do |note| %>
                    <div class="field_single">
                      <%= text_field_tag 'group[note][]', note %>
                      <%= image_tag 'delete.png', :alt => 'delete icon', :class => 'delete_icon click_remove_field_level1', :jq_tag_type => 'input' %>
                    </div>
                <% end %>
              </div>
            </td>
          </tr>
        </table>

        <%# Hidden fields %>
        <%= hidden_field_tag 'search_term', @search_term %>
        <%= hidden_field_tag 'group_field', @group_field %>

        <%# Submit %>
        <p style="margin-top: 10px">
          <% if @group.new_record? %>
              <%= f.submit 'Submit' %>
          <% else %>
              <%= f.submit 'Update' %>
          <% end %>
        </p>

      </div>

      <div style="clear: both"></div>
  <% end %>
</div>

app/views/groups/group_exists_list.erb
<%# User is directed to this page if they try to delete a group which is still being used %>
<div class="popup popup_subject">

  <div class="popup_title">Group Exists in Entry</div>

  <div><%= link_to 'Go back to search page', groups_path(@go_back_id, :search_term => @search_term, :group_field => @group_field) %></div>

  <div style="margin-top: 10px">
    The group <strong><%= @group_name %></strong> exists in one or more entries. Please remove it from the records displayed below (using the main interface) and then click on this button:
  </div>

  <%# Refresh button %>
  <div style="margin-top: 5px">
    <%= button_to 'Refresh', group_path(id), :method => :delete, params: { :search_term => @search_term, :group_field => @group_field }, title: "Delete '#{@group_name}'" %>
  </div>

  <div style="clear: both"></div>

  <hr/>

  <%# Display all the entries (with links) where the group still exists %>
  <div style="margin-top: 10px; margin-left: 0px">
    <% @existing_location_list.each do |t| %>
        <div style="margin-top: 5px">
          <%= link_to t[2], '#', :onclick => "window.opener.location.href='/entries?id=#{t[0]}&amp;folio_id=#{t[1]}&amp;set_folio=true'" %>
        </div>
    <% end %>
  </div>
</div>

app/views/groups/index.html.erb
<% context_path = ENV['CONTEXT_PATH'] %>

<div class="popup">

  <%# Display title %>
  <div class="popup_title">
    <% if @group_field == 'none' %>
        Organisation or Group List
    <% else %>
        Choose Organisation/Group Name Authority
    <% end %>
  </div>

  <%# Display links %>
  <div>
    <% if @group_field == 'none' %>
        <%= button_to "Add Group", new_group_path, method: :get, params: { :search_term => @search_term, :group_field => @group_field }, style: 'margin-top: -5px', title: 'Add element' %>
        <%= link_to 'Go back to admin page', admins_path, style: 'margin-left: 6px' %>
    <% else %>
        <%= link_to 'Click here to edit groups in the Admin interface', '#', onclick: "popup('#{context_path}/admins?start=true', 'admin'); return false;" %>
    <% end %>
  </div>

  <div style="clear: both"></div>

  <%# Search groups %>
  <%= form_tag groups_path, :method => :get, style: 'margin-top: 8px' do |f| %>
      <div class="search_box">
        <table>
          <tr>
            <td>Search Term:</td>
            <td><%= text_field_tag 'search_term', @search_term, class: 'text_field_search', id: 'search_box' %></td>
            <td>
              <%= submit_tag 'Search' %>
              <input type="button" value="Clear" onclick="reset_box(); return false"/>
            </td>
          </tr>
        </table>
      </div>
      <div style="clear: both"></div>
      <%= hidden_field_tag "group_field", @group_field %>
  <% end %>

  <div style="margin: 30px 0px 20px 2px">

    <%# Display search results %>
    <%
       if @search_array != nil && @search_array != ''
    %>

        <div style="font-size: 1.1em">
          Results: <strong><%= @search_array.size %></strong>
        </div>

        <div class="popup_search">

          <%# If this is in the admin section, allow user to edit, etc %>
          <% if @group_field == 'none' %>

              <table border='1' style="width: 100%; font-size: 1.1em; margin-top: 10px">

                <tr>
                  <th>Group or Organisation Name</th>
                  <th style="width: 60px">Edit</th>
                  <th style="width: 60px">Delete</th>
                </tr>

                <%
                   @search_array.each do |array_element|
                     id = array_element[0]
                     name = array_element[1]
                %>
                    <tr>
                      <td><%= name %></td>
                      <td style="width: 100px; text-align: center">
                        <%= button_to 'Edit', edit_group_path(id), :method => :get, params: { :search_term => @search_term, :group_field => @group_field }, title: 'Edit element' %>
                      </td>
                      <td style="width: 60px; text-align: center">
                        <%= button_to 'Delete', group_path(id), :method => :delete, params: { :search_term => @search_term, :group_field => @group_field }, title: 'Delete element', :data => { :confirm => "Are you sure you want to delete '#{name}'?" } %>
                      </td>
                    </tr>
                <% end %>

              </table>

          <%# Else just let the user click a link to choose a group because it has come from the entry form %>
          <% else %>
              <%
                 @search_array.each do |array_element|
                   id = array_element[0]
                   name = array_element[1]
              %>
                  <div style="margin-top: 5px; font-style: italic"><%= link_to name, '#', onClick: "post_value(\"#{name}\", '#{id}', '#{params[:group_field]}')", style: 'color: #7e2c2c' %></div>
              <% end %>
          <% end %>
        </div>
      <% end %>

      <%# Focus on search box %>
      <script>
            window.onload = function () {
                document.getElementById("search_box").focus();
            };
      </script>
    </div>

  </div>

app/views/groups/new.html.erb
<%= render "form" %>