config/routes.rb
Rails.application.routes.draw do

  mount Qa::Engine => '/qa'

  root 'login#index'

  resources :entries
  resources :concepts
  resources :places
  resources :people
  resources :groups
  resources :subjects
  resources :errors

  get 'image_zoom_large' => 'image_zoom_large#index'
  get 'image_zoom_large/alt' => 'image_zoom_large#alt'
  get 'logout' => 'login#logout'
  get 'login' => 'login#index'
  post 'login_submit' => 'login#login_submit'
  get 'login_temp' => 'login#login_temp'
  get 'timed_out' => 'login#timed_out'
  get 'landing_page' => 'landing_page#index'
  get 'browse_folios' => 'browse_folios#index'
  get 'go_entries' => 'landing_page#go_entries'
  get 'admins' => 'admins#index'

end

app/models/concept.rb
# frozen_string_literal: true

class Concept < ActiveFedora::Base
  include AssignRdfTypes
  include AssignId
  include DCTerms
  include SkosLabels
  include SameAs
  include Generic
  include RdfType

  belongs_to :concept_scheme, predicate: ::RDF::Vocab::SKOS.inScheme

  # Use only for Broader, Narrower will be added by default
  has_and_belongs_to_many :broader,
                          class_name: 'Concept',
                          predicate: ::RDF::Vocab::SKOS.broader,
                          inverse_of: :narrower
  has_and_belongs_to_many :narrower,
                          class_name: 'Concept',
                          predicate: ::RDF::Vocab::SKOS.narrower,
                          inverse_of: :broader

  property :definition, predicate: ::RDF::Vocab::SKOS.definition, multiple: false do |index|
    index.as :stored_searchable
  end

  property :see_also, predicate: ::RDF::Vocab::SKOS.related, multiple: true do |index|
    index.as :stored_searchable
  end

  # change this to has and belongs to many as doesn't save properly in latest version of AF
  #   property :broader, predicate: ::RDF::SKOS.broader, multiple: true do |index|
  #     index.as :stored_searchable
  #   end
  #
  #   property :narrower, predicate: ::RDF::SKOS.narrower, multiple: true do |index|
  #     index.as :stored_searchable
  #   end

  # there is more skos we could add ...
end

app/models/concepts/collection.rb
class Collection < ActiveFedora::Base
  include RdfType,Identifier

  #pcdm:Collection
  #http://fedora.info/definitions/v4/indexing#Indexable optional!

  has_many :conceptschemes
  has_many :concepts

end

app/models/concepts/concept.rb
require 'active_fedora/noid'

class Concept < ActiveFedora::Base
  include Identifier,RdfType,FormerId,AssignId,SameAs

  belongs_to :concept_scheme, predicate: ::RDF::SKOS.inScheme

  # skos:Concept
  # http://fedora.info/definitions/v4/indexing#Indexable

  property :preflabel, predicate: ::RDF::SKOS.prefLabel, multiple: false do |index|
    index.as :stored_searchable
  end

  property :altlabel, predicate: ::RDF::SKOS.altLabel, multiple: true do |index|
    index.as :stored_searchable
  end

  property :definition, predicate: ::RDF::SKOS.definition, multiple: false do |index|
    index.as :stored_searchable
  end

  property :broader, predicate: ::RDF::SKOS.broader, multiple: true do |index|
    index.as :stored_searchable
  end

  property :narrower, predicate: ::RDF::SKOS.narrower, multiple: true do |index|
    index.as :stored_searchable
  end

  # boolean
  property :istopconcept, predicate: ::RDF::URI.new('http://dlib.york.ac.uk/ontologies/generic#isTopConcept'), multiple: false do |index|
    index.as :stored_searchable
  end

  # boolean
  property :approved, predicate: ::RDF::URI.new('http://dlib.york.ac.uk/ontologies/generic#approved'), multiple: false do |index|
    index.as :stored_searchable
  end

  # there is more skos we could add ...

end

app/models/concepts/concept_scheme.rb
class ConceptScheme < ActiveFedora::Base
  include RdfType,Identifier,Title

  has_many :concepts
  has_many :collections
  belongs_to :collection, predicate: ::RDF::URI.new('http://fedora.info/definitions/v4/repository#hasParent')

  # skos:ConceptScheme
  #http://fedora.info/definitions/v4/indexing#Indexable

  # optional, use for nested subject headings schemes
  property :topconcept, predicate: ::RDF::SKOS.hasTopConcept, multiple: true do |index|
    index.as :stored_searchable
  end

  #etc.

end

app/controllers/concepts_controller.rb
# frozen_string_literal: true

class ConceptsController < ApplicationController
  before_action :session_timed_out_small

  layout 'admins'

  # INDEX
  def index
    # Set the list_type, e.g. 'data_role'
    @list_type = params[:list_type]

    # Set the search_term variable if it is passed as a parameter
    @search_term = ''
    @search_term = if !params[:search_term_index].nil?
                     params[:search_term_index]
                   else
                     params[:search_term]
                   end
    @safe_search_term = Regexp.escape(@search_term) unless @search_term.nil?
    @search_array = []

    # Get Concepts for the ConceptScheme and list type according to search_term
    SolrQuery.new.solr_query(q = 'has_model_ssim:Concept AND inScheme_ssim:' + get_concept_scheme_id(@list_type), fl = 'id, preflabel_tesim, altlabel_tesim, definition_tesim', rows = 1000, sort = 'id asc')['response']['docs'].map.each do |result|
      concept_id = result['id']
      preflabel = result['preflabel_tesim'].join

      next unless preflabel.match(/#{@safe_search_term}/i)

      tt = []
      tt << concept_id
      tt << preflabel
      altlabel = result['altlabel_tesim']
      altlabel = if !altlabel.nil?
                   altlabel
                 else
                   []
                 end
      tt << altlabel
      definition = result['definition_tesim']
      definition = definition.join unless definition.nil?
      tt << definition
      @search_array << tt
    end

    # Sort the array by preflabel
    @search_array = @search_array.sort_by { |k| k[1] }
  rescue StandardError => e
    log_error(__method__, __FILE__, e)
    raise
  end

  # SHOW
  def show; end

  # NEW
  def new
    @concept = Concept.new
    @search_term = params[:search_term]
    @list_type = params[:list_type]
  rescue StandardError => e
    log_error(__method__, __FILE__, e)
    raise
  end

  # EDIT
  def edit
    @concept = Concept.find(params[:id])
    @search_term = params[:search_term]
    @list_type = params[:list_type]
  rescue StandardError => e
    log_error(__method__, __FILE__, e)
    raise
  end

  # CREATE
  def create
    # Check parameters are permitted
    concept_params = whitelist_concept_params

    # Remove any empty fields
    remove_concept_popup_empty_fields(concept_params)

    @error = ''

    @error = "Please enter a 'Label'" if concept_params[:preflabel] == ''

    @concept = Concept.new(concept_params)

    # Go back to 'new' page if there is an error
    # Else save the concept and return to 'index' page
    if @error != ''
      @list_type = params[:list_type]
      @search_term = params[:search_term]
      render 'new'
    else
      @concept.concept_scheme_id = get_concept_scheme_id(params[:list_type])
      @concept.rdftype << @concept.add_rdf_types
      @concept.save
      redirect_to controller: 'concepts', action: 'index', search_term: params[:search_term], list_type: params[:list_type]
    end
  rescue StandardError => e
    log_error(__method__, __FILE__, e)
    raise
  end

  # UPDATE
  def update
    # Check parameters are permitted
    concept_params = whitelist_concept_params

    # Remove any empty fields
    remove_concept_popup_empty_fields(concept_params)

    @error = ''

    @error = "Please enter a 'Label'" if concept_params[:preflabel] == ''

    # Get a concept object using the id and populate it with the concept parameters
    @concept = Concept.find(params[:id])
    @concept.attributes = concept_params

    # Go back to 'new' page if there is an error
    # Else save the concept and return to 'index' page
    if @error != ''
      @search_term = params[:search_term]
      @list_type = params[:list_type]
      render 'edit'
    else
      @concept.save
      redirect_to controller: 'concepts', action: 'index', search_term: params[:search_term], list_type: params[:list_type]
    end
  rescue StandardError => e
    log_error(__method__, __FILE__, e)
    raise
  end

  # DESTROY
  def destroy
    @concept = Concept.find(params[:id])

    # Check if the concept is present in any of the entries
    # If so, direct the user to a page with the entry locations so that they can be removed
    existing_location_list = get_existing_location_list(params[:list_type], @concept.id)

    if !existing_location_list.empty?
      render 'concept_exists_list', locals: { :@concept_name => @concept.preflabel, :id => @concept.id, :@existing_location_list => existing_location_list, :@go_back_id => params[:go_back_id], :@search_term => params[:search_term], :@list_type => params[:list_type] }
    else
      @concept.destroy
      redirect_to controller: 'concepts', action: 'index', search_term: params[:search_term], list_type: params[:list_type]
    end
  rescue StandardError => e
    log_error(__method__, __FILE__, e)
    raise
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def whitelist_concept_params
    params.require(:concept).permit(:preflabel, :definition, altlabel: []) # Note - arrays need to go at the end or an error occurs!
  end
end

app/views/concepts/_form.html.erb
<div class="popup">

  <%
    if @concept.new_record?
      start_text = 'Add'
      form_url = 'concepts_path(@concept)'
      form_method = ':post'
    else
      start_text = 'Edit'
      form_url = 'concept_path(@concept)'
      form_method = ':patch'
    end
  %>

  <%# Display concept title %>
  <div class="popup_title">
    <%= start_text %> <%= capitalize_first_letter(@list_type) %>
  </div>

  <%# Display concept errors %>
  <% if @error != nil && @error != '' %>
      <div class="popup_error"><%= @error.html_safe %></div>
  <% end %>

  <%# Display 'Go Back' link %>
  <div>
    <%= link_to 'Go back to search page', concepts_path(:search_term => @search_term, :list_type => @list_type), style: "font-style: italic" %>
  </div>

  <%# Add / Edit concept form %>
  <%= form_for @concept, url: eval(form_url), method: eval(form_method), html: { style: 'margin-top: 15px; margin-bottom: 0px' } do |f| %>

      <div class='tab1'>

        <table cellspacing="0" style="width: 100%; font-size: 0.95em">

          <%# Label %>
          <tr>
            <th style="width: 120px">*Label:</th>
            <td>
              <%= text_field_tag "concept[preflabel]", @concept.preflabel %>
            </td>
          </tr>

          <%# Alternate Label %>
          <tr>
            <th>
              Alternate Label:
              <%= image_tag 'plus_sign.png', :alt => 'plus icon', :class => 'plus_icon click_popup_multiple_field_button', :jq_type_1 => 'concept', :jq_type_2 => 'altlabel', :context_path => ENV['CONTEXT_PATH'] %>
            </th>
            <td>
              <div class="field_group">
                <% @concept.altlabel.each do |altlabel| %>
                    <div class="field_single">
                      <%= text_field_tag 'concept[altlabel][]', altlabel %>
                      <%= image_tag 'delete.png', :alt => 'delete icon', :class => 'delete_icon_ click_remove_field_level1', :jq_tag_type => 'input' %>
                    </div>
                <% end %>
              </div>
            </td>
          </tr>

          <%# Definition %>
          <tr>
            <th>Definition:</th>
            <td>
              <%= text_field_tag "concept[definition]", @concept.definition %>
            </td>
          </tr>
        </table>

        <%# Hidden fields %>
        <%= hidden_field_tag 'search_term', @search_term %>
        <%= hidden_field_tag 'list_type', @list_type %>

        <%# Submit %>
        <p style="margin-top: 10px">
          <% if @concept.new_record? %>
              <%= f.submit 'Submit' %>
          <% else %>
              <%= f.submit 'Update' %>
          <% end %>
        </p>

      </div>

      <div style="clear: both"></div>

  <% end %>

</div>

app/views/concepts/concept_exists_list.erb
<%# User is directed to this page if they try to delete a concept which is still being used %>
<div class="popup popup_subject">

  <div class="popup_title">Concept Exists in Entry</div>

  <div><%= link_to 'Go back to search page', concepts_path(@go_back_id, :search_term => @search_term, :list_type => @list_type) %></div>

  <div style="margin-top: 10px">
    The concept <strong><%= @concept_name %></strong> exists in one or more entries. Please remove it from the records displayed below (using the main interface) and then click on this button:
  </div>

  <%# Refresh button %>
  <div style="margin-top: 5px">
    <%= button_to 'Refresh', concept_path(id), :method => :delete, params: { :search_term => @search_term, :list_type => @list_type }, title: "Delete '#{@concept_name}'" %>
  </div>

  <div style="clear: both"></div>

  <hr/>

  <%# Display all the entries (with links) where the concept still exists %>
  <div style="margin-top: 10px; margin-left: 0px">
    <% @existing_location_list.each do |t| %>
        <div style="margin-top: 5px">
          <%= link_to t[2], '#', :onclick => "window.opener.location.href='/entries?id=#{t[0]}&amp;folio_id=#{t[1]}&amp;set_folio=true'" %>
        </div>
    <% end %>
  </div>
</div>

app/views/concepts/edit.html.erb
<%= render "form" %>

app/views/concepts/index.html.erb
<div class="popup">

  <%# Display title %>
  <div class="popup_title"><%= capitalize_first_letter(@list_type) %></div>

  <%# Display links %>
  <div>
    <%= button_to "Add #{capitalize_first_letter(@list_type)}", new_concept_path, method: :get, params: {:search_term => @search_term, :list_type => @list_type}, style: 'margin-top: -5px' %>
    <%= link_to 'Go back to admin page', admins_path, style: 'margin-left: 6px' %>
  </div>

  <div style="clear: both"></div>

  <%# Search concepts %>
  <%= form_tag concepts_path, :method => :get, style: 'margin-top: 8px' do |f| %>
      <div class="search_box">
        <table>
          <tr>
            <td>Search Term:</td>
            <td><%= text_field_tag 'search_term', @search_term, class: 'text_field_search', id: 'search_box' %></td>
            <td style="padding-left: 0px">
              <%= submit_tag 'Search' %>
              <input type="button" value="Clear" onclick="reset_box(); return false"/>
            </td>
          </tr>
        </table>
      </div>
      <div style="clear: both"></div>
      <%= hidden_field_tag 'list_type', @list_type %>
  <% end %>

  <div style="margin: 30px 0px 20px 2px">

    <%# Display search results %>
    <%
       if @search_array != nil && @search_array != ''
    %>
        <div style="font-size: 1.1em">
          Results: <strong><%= @search_array.size %></strong>
        </div>

        <div style="clear: both"></div>

        <div class="popup_search">

          <table border='1' style="width: 100%; font-size: 1.1em; margin-top: 10px">

            <tr>
              <th>Label</th>
              <th>Alternate Label(s)</th>
              <th>Definition</th>
              <th style="width: 60px">Edit</th>
              <th style="width: 60px">Delete</th>
            </tr>

            <%
               @search_array.each do |array_element|
                 id = array_element[0]
                 label = array_element[1]
                 altlabel = array_element[2]
                 definition = array_element[3]
            %>
                <tr>
                  <td><%= label %></td>
                  <td>
                    <%
                       altlabel.each do |tt|
                    %>
                        <%= tt %>
                        <br/>
                    <%
                       end
                    %>
                  </td>
                  <td><%= definition %></td>
                  <td style="width: 100px; text-align: center">
                    <%= button_to 'Edit', edit_concept_path(id), :method => :get, params: { :search_term => @search_term, :list_type => @list_type }, title: 'Edit element' %>
                  </td>
                  <td style="width: 60px; text-align: center">
                    <%= button_to 'Delete', concept_path(id), :method => :delete, params: { :search_term => @search_term, :list_type => @list_type }, title: 'Delete element', :data => { :confirm => "Are you sure you want to delete '#{label}'?" } %>
                  </td>
                </tr>
            <% end %>
          </table>
        </div>
    <% end %>

    <%# Focus on search box %>
    <script>
        window.onload = function () {
            document.getElementById("search_box").focus();
        };
    </script>
  </div>

</div>

app/views/concepts/new.html.erb
<%= render "form" %>