config/routes.rb
Rails.application.routes.draw do

  mount Qa::Engine => '/qa'

  root 'login#index'

  resources :entries
  resources :concepts
  resources :places
  resources :people
  resources :groups
  resources :subjects
  resources :errors

  get 'image_zoom_large' => 'image_zoom_large#index'
  get 'image_zoom_large/alt' => 'image_zoom_large#alt'
  get 'logout' => 'login#logout'
  get 'login' => 'login#index'
  post 'login_submit' => 'login#login_submit'
  get 'login_temp' => 'login#login_temp'
  get 'timed_out' => 'login#timed_out'
  get 'landing_page' => 'landing_page#index'
  get 'browse_folios' => 'browse_folios#index'
  get 'go_entries' => 'landing_page#go_entries'
  get 'admins' => 'admins#index'

end

app/models/place.rb
# frozen_string_literal: true

class Place < ActiveFedora::Base
  include AssignRdfTypes
  include Generic
  include RdfsSeealso
  include DCTerms
  include MadsRelauth
  include SkosLabels
  include SameAs
  include AssignId
  include RdfType

  belongs_to :concept_scheme, predicate: ::RDF::Vocab::SKOS.inScheme

  # eg. NCARules name.
  property :place_name, predicate: ::RDF::URI.new('http://www.geonames.org/ontology#name'), multiple: false do |index|
    index.as :stored_searchable
  end

  # eg. NCARules civil parish.
  property :parent_ADM4, predicate: ::RDF::URI.new('http://www.geonames.org/ontology#parentADM4'), multiple: false do |index|
    index.as :stored_searchable
  end

  # eg. NCARules local administrative unit
  property :parent_ADM3, predicate: ::RDF::URI.new('http://www.geonames.org/ontology#parentADM3'), multiple: false do |index|
    index.as :stored_searchable
  end
  # eg. NCARules county/wider administrative unit
  property :parent_ADM2, predicate: ::RDF::URI.new('http://www.geonames.org/ontology#parentADM2'), multiple: false do |index|
    index.as :stored_searchable
  end

  # eg. NCARules country (England)
  property :parent_ADM1, predicate: ::RDF::URI.new('http://www.geonames.org/ontology#parentADM1'), multiple: false do |index|
    index.as :stored_searchable
  end

  # eg. UK
  property :parent_country, predicate: ::RDF::URI.new('http://www.geonames.org/ontology#parentCountry'), multiple: false do |index|
    index.as :stored_searchable
  end

  # use http://unlock.edina.ac.uk/ws/supportedFeatureTypes?&gazetteer=deep&format=json
  property :feature_code, predicate: ::RDF::URI.new('http://dlib.york.ac.uk/ontologies/borthwick-registers#featureType'), multiple: true do |index|
    index.as :stored_searchable
  end

  property :note, predicate: ::RDF::URI.new('http://dlib.york.ac.uk/ontologies/borthwick-registers#note'), multiple: true do |index|
    index.as :stored_searchable
  end
end

app/controllers/places_controller.rb
# frozen_string_literal: true

class PlacesController < ApplicationController
  include PlacesHelper

  before_action :session_timed_out_small

  # INDEX
  def index
    # This variable identifies the 'Same As' field on the form (i.e. it is used when the user selects a 'place')
    @place_field = params[:place_field]

    # Set the search_term variable if it is passed as a parameter
    @search_term = ''
    if !params[:search_term_index].nil?
      @search_term = params[:search_term_index]
    elsif !params[:search_term].nil?
      @search_term = params[:search_term]
    end
    @safe_search_term = Regexp.escape(@search_term) unless @search_term.nil?
    @search_array = []

    # Get Concepts for the Place ConceptScheme and filter according to search_term
    # solr_query(q, fl, rows, sort) expected parameters
    num = SolrQuery.new.solr_query('has_model_ssim:Place', 'id', 0)['response']['numFound']
    search_response = SolrQuery.new.solr_query(
      'has_model_ssim:Place',
      'id, place_name_tesim, altlabel_tesim, parent_ADM4_tesim, parent_ADM3_tesim, parent_ADM2_tesim, parent_ADM1_tesim',
      num,
      'id asc'
    )

    search_response['response']['docs'].map.each do |result|
      id = result['id']
      place_name = result['place_name_tesim']
      parent_ADM4 = result['parent_ADM4_tesim']
      parent_ADM3 = result['parent_ADM3_tesim']
      parent_ADM2 = result['parent_ADM2_tesim']
      parent_ADM1 = result['parent_ADM1_tesim']
      # Some places do not have variant name
      altlabel = ''
      altlabel = result['altlabel_tesim'].join unless result['altlabel_tesim'].nil?

      tt = []
      name = get_label(true, place_name, parent_ADM4, parent_ADM3, parent_ADM2, parent_ADM1)

      # Select results that match place name or place variant name
      next unless name.match(/#{@safe_search_term}/i) || altlabel.match(/#{@safe_search_term}/i)

      tt << id
      tt << name
      @search_array << tt
    end

    # Sort the array by place_name
    @search_array = @search_array.sort_by { |k| k[1] }
  rescue StandardError => e
    log_error(__method__, __FILE__, e)
    raise
  end

  # SHOW
  def show; end

  # NEW
  def new
    @place = Place.new
    @search_term = params[:search_term]
    @place_field = params[:place_field]
  rescue StandardError => e
    log_error(__method__, __FILE__, e)
    raise
  end

  # EDIT
  def edit
    @place = Place.find(params[:id])
    @search_term = params[:search_term]
    @place_field = params[:place_field]
  rescue StandardError => e
    log_error(__method__, __FILE__, e)
    raise
  end

  # CREATE
  def create
    # Check parameters are permitted
    place_params = whitelist_place_params

    # Remove any empty fields
    remove_place_popup_empty_fields(place_params)

    @error = ''

    @error = "Please enter a 'Place Name'" if place_params[:place_name] == ''

    # Check that same_as is a URL
    @error = check_url(place_params[:same_as], @error, 'Same As')

    # Disable this check
    # Check that related_authority is a URL
    # @error = check_url(place_params[:related_authority], @error, "Related Authority")

    @place = Place.new(place_params)

    if @error != ''
      @search_term = params[:search_term]
      @place_field = params[:place_field]
      render 'new'
    else

      # Use a solr query to obtain the concept scheme id for 'places'
      response = SolrQuery.new.solr_query(q = 'has_model_ssim:ConceptScheme AND preflabel_tesim:"places"', fl = 'id', rows = 1, sort = '')
      id = response['response']['docs'][0]['id']
      @place.concept_scheme_id = id

      # Get preflabel, rdftype and save
      @place.preflabel = get_label(false, @place.place_name, @place.parent_ADM4, @place.parent_ADM3, @place.parent_ADM2, @place.parent_ADM1)
      @place.rdftype << @place.add_rdf_types
      @place.save

      # If the 'Submit and Close' button has been clicked, pass these variables back to the page
      # so that the javascript method is run (i.e. post_value()) and the page is closed
      if params[:commit] == 'Submit and Close'
        @commit_id = @place.id
        @commit_place_name = place_params[:place_name]
      end

      redirect_to controller: 'places', action: 'index', search_term: params[:search_term], place_field: params[:place_field]
    end
  rescue StandardError => e
    log_error(__method__, __FILE__, e)
    raise
  end

  # UPDATE
  def update
    # Check parameters are permitted
    place_params = whitelist_place_params

    # Remove any empty fields
    remove_place_popup_empty_fields(place_params)

    @error = ''

    @error = "Please enter a 'Place Name'" if place_params[:place_name] == ''

    # Check that same_as is a URL
    @error = check_url(place_params[:same_as], @error, 'Same As')

    # Disable this check
    # Check that related_authority is a URL
    # @error = check_url(place_params[:related_authority], @error, "Related Authority")

    # Get a place object using the id and populate it with the place parameters
    @place = Place.find(params[:id])
    @place.attributes = place_params

    if @error != ''
      @search_term = params[:search_term]
      @place_field = params[:place_field]
      render 'edit'
    else
      @place.preflabel = get_label(false, @place.place_name, @place.parent_ADM4, @place.parent_ADM3, @place.parent_ADM2, @place.parent_ADM1)
      @place.save
      # solr update any related objects
      update_related('place', @place.id)
      redirect_to controller: 'places', action: 'index', place_field: 'none', search_term: params[:search_term]
    end
  rescue StandardError => e
    log_error(__method__, __FILE__, e)
    raise
  end

  # DESTROY
  def destroy
    # If this is an external place, skip to the redirect
    unless params[:id].start_with? 'deep_'
      @place = Place.find(params[:id])
      # Check if the place is present in any of the entries
      # If so, direct the user to a page with the entry locations so that they can remove them
      existing_location_list = get_existing_location_list('place_same_as', @place.id)

      if !existing_location_list.empty?
        render 'place_exists_list', locals: { :@place_name => @place.place_name, :id => @place.id, :@existing_location_list => existing_location_list, :@go_back_id => params[:go_back_id], :@search_term => params[:search_term], :@place_field => params[:place_field] }
      else
        @place.destroy
        redirect_to controller: 'places', action: 'index', search_term: params[:search_term], place_field: params[:place_field]
      end
    end
  rescue StandardError => e
    log_error(__method__, __FILE__, e)
    raise
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def whitelist_place_params
    params.require(:place).permit(:place_name, :unlock, :auth, :is_deep_checked, :parent_ADM4, :parent_ADM3, :parent_ADM2, :parent_ADM1, :parent_country, feature_code: [], same_as: [], related_authority: [], altlabel: [], note: []) # Note - arrays need to go at the end or an error occurs!
  end
end

app/helpers/places_helper.rb
module PlacesHelper

  # Check the DEEP or OS id, if it's not a local id, create a new place
  def check_id id, gaz='deep'
    if id.start_with? 'deep_'
      create_new_place(id,gaz)
    else
      id
    end
  end

  # This method is used to get the preflabel and to get the label which is displayed on the view page
  # is_join is required if the data comes from solr, i.e. when getting the data to display on the view page
  def get_label(is_join, place_name, parent_ADM4, parent_ADM3, parent_ADM2, parent_ADM1, feature_code=nil, url=nil)

    name = ''

    if place_name != nil and place_name != ''
      if is_join == true then
        place_name = place_name.join
      end
      name = place_name
    end

    if parent_ADM4 != nil and parent_ADM4 != ''
      if is_join == true then
        parent_ADM4 = parent_ADM4.join
      end
      if name != '' then
        name = "#{name},"
      end
      name = "#{name} #{parent_ADM4}"
    end

    if parent_ADM3 != nil and parent_ADM3 != ''
      if is_join == true then
        parent_ADM3 = parent_ADM3.join
      end
      if name != '' then
        name = "#{name},"
      end
      name = "#{name} #{parent_ADM3}"
    end

    if parent_ADM2 != nil and parent_ADM2 != ''
      if is_join == true then
        parent_ADM2 = parent_ADM2.join
      end
      if name != '' then
        name = "#{name},"
      end
      name = "#{name} #{parent_ADM2}"
    end

    if parent_ADM1 != nil and parent_ADM1 != ''
      if is_join == true then
        parent_ADM1 = parent_ADM1.join
      end
      if name != '' then
        name = "#{name},"
      end
      name = "#{name} #{parent_ADM1}"
    end

    if feature_code != nil and feature_code != ''
      if name != '' then
        name = "#{name} (Type: #{feature_code})"
      end
    end

    if url != nil and url != ''
      if name != '' then
        name = "#{name} (<a href=\"#{url}\" target=\"_blank\">Gazetteer</a>)"
      end
    end

    return name
  end

  private

  def create_new_place id,gaz
    response = SolrQuery.new.solr_query(q='same_as_tesim:"' + "http://unlock.edina.ac.uk/ws/search?name=#{id.gsub('deep_', '')}&format=json" + '"', fl='id', rows=1)['response']
    if response['numFound'] == 0
      @place = Place.new
      if gaz == 'deep'
        auth = Deep.new('subauthority')
        build_place(auth,id)
        if @place.id.nil?
          auth = OrdnanceSurvey.new('subauthority')
          build_place(auth,id,'os')
        end
      elsif gaz == 'os'
        auth = OrdnanceSurvey.new('subauthority')
        build_place(auth,id,'os')
      end
    else
      @place = Place.find(response['docs'][0]['id'])
    end
    @place.id
  end

  # Create a new place with data from DEEP / OS
  def build_place auth,id,gaz='deep'
    auth.search_by_id(id.gsub('deep_','')).each do |result|
      @place.rdftype = @place.add_rdf_types
      if gaz == 'deep'
        @place.same_as = ["http://unlock.edina.ac.uk/ws/search?name=#{id.gsub('deep_','')}&gazetteer=deep&format=json"]
      else
        @place.same_as = ["http://unlock.edina.ac.uk/ws/search?name=#{id.gsub('deep_','')}&format=json"]
      end
      @place.place_name = result['name']
      @place.parent_ADM4 = result['adminlevel4']
      @place.parent_ADM3 = result['adminlevel3']
      @place.parent_ADM2 = result['adminlevel2']
      @place.parent_ADM1 = result['adminlevel1']
      @place.feature_code = [result['featuretype']]
      unless result['uricdda'].nil?
        @place.related_authority << [result['uricdda']]
      end
      @place.preflabel = get_label(false, @place.place_name, @place.parent_ADM4, @place.parent_ADM3, @place.parent_ADM2, @place.parent_ADM1)
      # Use a solr query to obtain the concept scheme id for 'places'
      response = SolrQuery.new.solr_query(q='has_model_ssim:ConceptScheme AND preflabel_tesim:"places"', fl='id', rows=1, sort='')
      @place.concept_scheme_id = response['response']['docs'][0]['id']
      @place.save
    end
  end

end

app/views/places/_form.html.erb
<div class="popup">

  <%
     if @place.new_record?
      start_text = 'Add'
      form_url = 'places_path(@place)'
      form_method = ':post'
    else
      start_text = 'Edit'
      form_url = 'place_path(@place)'
      form_method = ':patch'
    end
  %>

  <%# Display place title %>
  <div class="popup_title">
    <%= start_text %> Place
  </div>

  <%# Display place errors %>
  <% if @error != nil && @error != '' %>
      <div class="popup_error"><%= @error.html_safe %></div>
  <% end %>

  <%# Display 'Go Back' link %>
  <div>
    <%= link_to 'Go back to search page', places_path(:search_term => @search_term, :place_field => @place_field) %>
  </div>

  <%# Add / Edit place form %>
  <%= form_for @place, url: eval(form_url), method: eval(form_method), html: { style: 'margin-top: 15px; margin-bottom: 0px' } do |f| %>

      <div class='tab1'>

        <table cellspacing="0" style="width: 100%; font-size: 0.95em">

          <%# Place Name %>
          <tr>
            <th style="width: 150px">*Place Name:</th>
            <td>
              <%= text_field_tag "place[place_name]", @place.place_name %>
            </td>
          </tr>

          <%# Civil Parish or Township (place_ADM4) %>
          <tr>
            <th>Civil Parish or Township:</th>
            <td>
              <%= text_field_tag "place[parent_ADM4]", @place.parent_ADM4 %>
            </td>
          </tr>

          <%# Town, City or District (place_ADM3) %>
          <tr>
            <th>Town, City or District:</th>
            <td>
              <%= text_field_tag "place[parent_ADM3]", @place.parent_ADM3 %>
            </td>
          </tr>

          <%# County (place_ADM2) %>
          <tr>
            <th>County:</th>
            <td>
              <%= text_field_tag "place[parent_ADM2]", @place.parent_ADM2 %>
            </td>
          </tr>

          <%# Country (e.g. England) (place_ADM1) %>
          <tr>
            <th>Country (e.g. England):</th>
            <td>
              <%= text_field_tag "place[parent_ADM1]", @place.parent_ADM1 %>
            </td>
          </tr>

          <%# Country (parent_country) %>
          <tr>
            <th>Country:</th>
            <td>
              <%= text_field_tag "place[parent_country]", @place.parent_country %>
            </td>
          </tr>

          <%# Place Type (feature_code) %>
          <tr>
            <th>Place Type:
              <%= image_tag 'plus_sign.png', :alt => 'plus icon', :class => 'plus_icon click_popup_multiple_field_button', :jq_type_1 => 'place', :jq_type_2 => 'feature_code', :context_path => ENV['CONTEXT_PATH'] %>
            </th>
            <td>
              <div class="field_group">
                <% @place.feature_code.each do |feature_code| %>
                    <div class="field_single">
                      <%= text_field_tag 'place[feature_code][]', feature_code %>
                      <%= image_tag 'delete.png', :alt => 'delete icon', :class => 'delete_icon click_remove_field_level1', :jq_tag_type => 'input' %>
                    </div>
                <% end %>
              </div>
            </td>
          </tr>

          <%# Same As %>
          <tr>
            <th>Same As:
              <%= image_tag 'plus_sign.png', :alt => 'plus icon', :class => 'plus_icon click_popup_multiple_field_button', :jq_type_1 => 'place', :jq_type_2 => 'same_as', :context_path => ENV['CONTEXT_PATH'] %>
            </th>
            <td>
              <div class="same_as">
                <% @place.same_as.each do |same_as| %>
                    <div class="field_single">
                      <%= text_field_tag 'place[same_as][]', same_as %>
                      <%= image_tag 'delete.png', :alt => 'delete icon', :class => 'delete_icon click_remove_field_level1', :jq_tag_type => 'input' %>
                    </div>
                <% end %>
              </div>
            </td>
          </tr>

          <%# Related Authority %>
          <tr>
            <th>Related Authority:
              <%= image_tag 'plus_sign.png', :alt => 'plus icon', :class => 'plus_icon click_popup_multiple_field_button', :jq_type_1 => 'place', :jq_type_2 => 'related_authority', :context_path => ENV['CONTEXT_PATH'] %>
            </th>
            <td>
              <div class="field_group">
                <% @place.related_authority.each do |related_authority| %>
                    <div class="field_single">
                      <%= text_field_tag 'place[related_authority][]', related_authority %>
                      <%= image_tag 'delete.png', :alt => 'delete icon', :class => 'delete_icon click_remove_field_level1', :jq_tag_type => 'input' %>
                    </div>
                <% end %>
              </div>
            </td>
          </tr>

          <%# Variant Names %>
          <%# Note that this is 'altlabel' in the model %>
          <tr>
            <th>Variant Names:
              <%= image_tag 'plus_sign.png', :alt => 'plus icon', :class => 'plus_icon click_popup_multiple_field_button', :jq_type_1 => 'place', :jq_type_2 => 'altlabel', :context_path => ENV['CONTEXT_PATH'] %>
            </th>
            <td>
              <div class="field_group">
                <% @place.altlabel.each do |altlabel| %>
                    <div class="field_single">
                      <%= text_field_tag 'place[altlabel][]', altlabel %>
                      <%= image_tag 'delete.png', :alt => 'delete icon', :class => 'delete_icon click_remove_field_level1', :jq_tag_type => 'input' %>
                    </div>
                <% end %>
              </div>
            </td>
          </tr>
            <%# Note %>
            <tr>
                <th>Note:
                  <%= image_tag 'plus_sign.png', :alt => 'plus icon', :class => 'plus_icon click_popup_multiple_field_button', :jq_type_1 => 'place', :jq_type_2 => 'note', :context_path => ENV['CONTEXT_PATH'] %>
                </th>
                <td>
                    <div class="note">
                        <% @place.note.each do |note| %>
                            <div class="field_single">
                                <%= text_field_tag 'place[note][]', note %>
                              <%= image_tag 'delete.png', :alt => 'delete icon', :class => 'delete_icon click_remove_field_level1', :jq_tag_type => 'input' %>
                            </div>
                        <% end %>
                    </div>
                </td>
            </tr>
        </table>

        <%# Hidden fields %>
        <%= hidden_field_tag 'search_term', @search_term %>
        <%= hidden_field_tag 'place_field', @place_field %>

        <%# Submit %>
        <p style="margin-top: 10px">
          <% if @place.new_record? %>
              <%= f.submit 'Submit' %>
          <% else %>
              <%= f.submit 'Update' %>
          <% end %>
        </p>

      </div>

      <div style="clear: both"></div>
      
  <% end %>

</div>

app/views/places/edit.html.erb
<%= render "form" %>

app/views/places/index.html.erb
<% context_path = ENV['CONTEXT_PATH'] %>

<div class="popup">

  <%# Display title %>
  <div class="popup_title">
    <% if @place_field == 'none' %>
        Place List
    <% else %>
        Choose Place Name Authority
    <% end %>
  </div>

  <%# Display links %>
  <div>
    <% if @place_field == 'none' %>
        <%= button_to "Add Place", new_place_path, method: :get, params: {:search_term => @search_term, :place_field => @place_field}, style: 'margin-top: -5px', title: 'Add element' %>
        <%= link_to 'Go back to admin page', admins_path, style: 'margin-left: 6px' %>
    <% else %>
        <%= link_to 'Click here to edit places in the Admin interface', '#', onclick: "popup('#{context_path}/admins?start=true', 'admin'); return false;" %>
    <% end %>
  </div>

  <div style="clear: both"></div>

  <%# Search places %>
  <%= form_tag places_path, :method => :get, style: 'margin-top: 8px' do |f| %>
      <div class="search_box">
        <table>
          <tr>
            <td>Search Term:</td>
            <td><%= text_field_tag 'search_term_index', @search_term, class: 'text_field_search', id: 'search_box' %></td>
            <td>
              <%= submit_tag 'Search' %>
              <input type="button" value="Clear" onclick="reset_box(); return false"/>
            </td>
          </tr>
        </table>
      </div>
      <div style="clear: both"></div>
      <%= hidden_field_tag 'place_field', @place_field %>
  <% end %>

  <div style="margin: 30px 0px 20px 2px">

    <%# Display search results %>
    <%
       if @search_array != nil && @search_array != ''
    %>

        <div style="font-size: 1.1em">
          Results: <strong><%= @search_array.size %></strong> <% if @deep_checked %> from <%=  @deep_checked.upcase %> <% end %>
        </div>

        <div style="clear: both"></div>

        <div class="popup_search">

          <%# If this is in the admin section, allow user to edit, etc %>
          <% if @place_field == 'none' or @deep_checked %>

              <table border='1' style="width: 100%; font-size: 1.1em; margin-top: 10px">

                <tr>
                  <th>Place Name</th>
                <%
                   unless @deep_checked
                     button = 'Edit'
                %>
                      <th style="width: 60px">Edit</th>
                      <th style="width: 60px">Delete</th>
                  <%
                   else
                     button = 'Choose'
                  %>
                      <th style="width: 120px">Add to Places</th>
                  <%
                   end

                   @search_array.each do |array_element|
                     id = array_element[0]
                     name = array_element[1].html_safe
                    %>

                    </tr>
                    <tr>
                      <td><%= name %></td>
                      <td style="width: 100px; text-align: center">
                        <%= button_to button, edit_place_path(id), :method => :get, params: {:search_term => @search_term, :place_field => @place_field, :is_deep_checked => @deep_checked}, title: 'Edit element' %>
                      </td>
                      <% unless @deep_checked %>
                        <td style="width: 60px; text-align: center">
                          <%= button_to 'Delete', place_path(id), :method => :delete, params: {:search_term => @search_term, :place_field => @place_field}, title: 'Delete element', :data => {:confirm => "Are you sure you want to delete '#{name}'?"} %>
                        </td>
                      <% end %>
                    </tr>
                <% end %>

              </table>

          <%# Else just let the user click a link to choose a person because it has come from the entry form %>
          <% else %>
              <%
                 @search_array.each do |array_element|
                   id = array_element[0]
                   name = array_element[1]
              %>
                  <div style="margin-top: 5px">
                      <%= link_to name, '#', onClick: "post_value(\"#{name}\", '#{id}', '#{params[:place_field]}')", style: 'color: #7e2c2c; font-style: italic' %>
                  </div>
              <% end %>
          <% end %>
        </div>
    <% end %>

    <%# Focus on search box %>
    <script>
        window.onload = function () {
            document.getElementById("search_box").focus();
        };
    </script>
  </div>

</div>

app/views/places/new.html.erb
<%= render "form" %>

app/views/places/place_exists_list.erb
<%# User is directed to this page if they try to delete a place which is still being used %>
<div class="popup popup_subject">

  <div class="popup_title">Place Exists in Entry</div>

  <div><%= link_to 'Go back to search page', places_path(@go_back_id, :search_term => @search_term, :place_field => @place_field) %></div>

  <div style="margin-top: 10px">
    The place <strong><%= @place_name %></strong> exists in one or more entries. Please remove it from the records displayed below (using the main interface) and then click on this button:
  </div>

  <%# Refresh button %>
  <div style="margin-top: 5px">
    <%= button_to 'Refresh', place_path(id), :method => :delete, params: { :search_term => @search_term, :place_field => @place_field }, title: "Delete '#{@place_name}'" %>
  </div>

  <div style="clear: both"></div>

  <hr/>

  <%# Display all the entries (with links) where the place still exists %>
  <div style="margin-top: 10px; margin-left: 0px">
    <% @existing_location_list.each do |t| %>
        <div style="margin-top: 5px">
          <%= link_to t[2], '#', :onclick => "window.opener.location.href='/entries?id=#{t[0]}&amp;folio_id=#{t[1]}&amp;set_folio=true'" %>
        </div>
    <% end %>
  </div>
</div>